### ISSUE TITLE
How to add a toast from outside react component? 

### ISSUE THREAD

**Issue by brielov** [jossmac/react-toast-notifications#112]
Hi, I don't know if it is possible, but it would be nice to add toast notifications, in my case, from apollo link error.

**Comment by CicheR** [comment]
I used a simple approach: _**passing the hook instance** to the place where the notification should be raised_

You can do it in many ways, the simplest ones could be: 
- As a _parameter_ (which can be tedious and error-prone if you have to add the parameter in many places)
- As a _module variable_ (or any other _global_ mechanism)

In my case I did it with a variable in the module from where I want to raise the notifications:
![image](https://user-images.githubusercontent.com/46723276/86994870-b31ecb00-c1e6-11ea-9be9-ae239532ac5b.png)

---

Maybe this is not the best _“clean code / architecturally brilliant”_ approach, but it works just fine for the needs of the project. 🤓👍

Otherwise, maybe you can try [react-toastify](https://github.com/fkhadra/react-toastify), which uses a _function_ approach (not a hook) to raise the notifications.

**Comment by brielov** [comment]
@CicheR Thanks, that looks good!
