### ISSUE TITLE
How to make it show up in fullscreen mode?

### ISSUE THREAD

**Issue by miliu99** [jossmac/react-toast-notifications#147]
It shows in regular screens, but I couldn't make it show up in fullscreen mode - did I miss any options or is it not supported?

**Comment by jossmac** [comment]
Just to be sure, you mean when an element has been made fullscreen using the [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API)?

I've never tried that, but it could just be a `z-index` issue. Please provide a reproduction using [CodeSandbox](https://codesandbox.io/) if you don't resolve the issue.

**Comment by miliu99** [comment]
Hi Joss, yes that's right.

I just created a sandbox project at
https://codesandbox.io/s/musing-frog-5v3fs?fontsize=14&hidenavigation=1&theme=dark
.

However, in this environment, the fullscreen API doesn't seem to work and I
got an error when trying to make it fullscreen.

[image: image.png]

Thanks!
Ming

**Comment by jossmac** [comment]
Thanks for that @miliu99

After some digging, appears to be by design that fullscreen elements trump stacking contexts. Knowing that now, it makes sense that elements outside of the fullscreen element will not be visible. This is because of the [portal](https://reactjs.org/docs/portals.html) used to render the toast container.

**Comment by miliu99** [comment]
Good to know...Thank you very much for the update, Joss.
