### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by onyekaa** [jossmac/react-toast-notifications#9]
Hi, so I tried the demo, looks great, almost exactly what I want. I just have a question, because it's not clear in the docs: Must the notifying block of code always be wrapped with `withToastManager`? I ask because, in a situation where say, I want an imported function to return a toast if successful, like so:

```js
const saveThing = (data, {content, toast }) => {
   somefunction(data).then(resp => {
      // send success message
      // ideally I would be able to do this:
      toast.add('Saved!', { appearance: 'success' })
   }
}
export { saveThing }

<SomeComponent onClick={saveThing} />
```
Once I wrap the function in the `withToastManager` the function stops working completely. I know it has to do with the way it's being called but I'm still kind of new to React and feel like I might be missing something. I thought it was expecting a Component, but the demo implies not. How do I call in a situation like this?

**Comment by jossmac** [comment]
Hi @onyekaa,

The `withToastManager` is a [higer-order component](https://reactjs.org/docs/higher-order-components.html), which we use to augment a given component by providing the toast manager's methods as props, via [`context`](https://reactjs.org/docs/context.html). You're getting errors because the function is expecting a component as its only argument.

You could achieve something similar to above using a [render prop](https://reactjs.org/docs/render-props.html):

```jsx
class SaveComponent extends React.Component {
  saveThing = (data) => {
    const { toastManager } = this.props;
    
    somefunction(data).then(resp => {
      toastManager.add('Saved!', { appearance: 'success' })
    }
  }
  render() {
    this.props.children(this.saveThing)
  }
}

const SaveProvider = withToastManager(SaveComponent);

// elsewhere

const SomeComponent = (props) => (
  <SaveProvider>
    {saveThing => (
      <button onClick={saveThing}>
        {/* ... */}
      </button>
    )}
  </SaveProvider>
);
```
